name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - name: Check out repository code of ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Clone Scripts repository
        uses: actions/checkout@main
        with:
          repository: andresnboza/reloadAppScripts
          path: ./reloadAppScripts
      - name: List files in scripts folder
        run: |
          cp ReadmeAppService3.md reloadAppScripts/ReadmeAppService3.md && cd reloadAppScripts && ls
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dnspython
          pip install bson
          pip install pymongo
      - name: Execute the save
        run: |
          echo '--> Start of the save'
          cd reloadAppScripts
          python save2.py ${{ secrets.FILE_NAME }} ${{ secrets.MONGO_URI }}
          echo '--> End of the save'
      - run: echo "ğŸ This job's status is ${{ job.status }}."
